package com.cb.passwdbox.greendao.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.cb.passwdbox.greendao.model.Password;
import com.cb.passwdbox.greendao.model.PwdType;

import com.cb.passwdbox.greendao.db.PasswordDao;
import com.cb.passwdbox.greendao.db.PwdTypeDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig passwordDaoConfig;
    private final DaoConfig pwdTypeDaoConfig;

    private final PasswordDao passwordDao;
    private final PwdTypeDao pwdTypeDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        passwordDaoConfig = daoConfigMap.get(PasswordDao.class).clone();
        passwordDaoConfig.initIdentityScope(type);

        pwdTypeDaoConfig = daoConfigMap.get(PwdTypeDao.class).clone();
        pwdTypeDaoConfig.initIdentityScope(type);

        passwordDao = new PasswordDao(passwordDaoConfig, this);
        pwdTypeDao = new PwdTypeDao(pwdTypeDaoConfig, this);

        registerDao(Password.class, passwordDao);
        registerDao(PwdType.class, pwdTypeDao);
    }
    
    public void clear() {
        passwordDaoConfig.clearIdentityScope();
        pwdTypeDaoConfig.clearIdentityScope();
    }

    public PasswordDao getPasswordDao() {
        return passwordDao;
    }

    public PwdTypeDao getPwdTypeDao() {
        return pwdTypeDao;
    }

}
